### ISSUE TITLE
Support UTF 8

### ISSUE THREAD

**Issue by shawkynasr** [xulihang/Aligner#3]
Could you plaese support Arabic (UTF-8)?

**Comment by xulihang** [comment]
Which file format are you using? If you use txt files, save them in UTF-8 encoding. Aligner should support Arabic.

**Comment by shawkynasr** [comment]
Yes, I am using txt, but no option to choose Arabic, not at list

**Comment by xulihang** [comment]
You can manually enter the language code for Arabic, which is ar.

**Comment by shawkynasr** [comment]
Ok, I will try it. Thanks!
